### ISSUE TITLE
List remote method names

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-component-explorer#124]
We should make it easier for developers to map APIs to actual remote methods. I think listing this in the UI would be enough.

/cc @crandmck

**Comment by bajtos** [comment]
@ritch I am not sure if I understand your request. Are you asking the swagger generator and/or the explorer UI to include the remote method name (e.g. `create`) in the description of its route (e.g. `POST /Cars`)?

**Comment by bajtos** [comment]
FWIW, I believe the swagger metadata already includes remote method name as the route `id`.

**Comment by ritch** [comment]
Yes just displaying it in the user interface

**Comment by crandmck** [comment]
+1 I think that's a great suggestion.

**Comment by dmtux** [comment]
In case of deprecated https://github.com/strongloop/strong-swagger-ui fork it depends on swagger-ui issue https://github.com/swagger-api/swagger-ui/issues/1273

**Comment by toniopelo** [comment]
This is actually something quite useful if I understand well the purpose of this issue.
Mapping the remote method name with the REST endpoint could be a time saver when you want to programmatically access some method or whatever :) 👍

**Comment by bajtos** [comment]
AFAICT, Swagger UI has a config option to enable display of operation ids - see https://github.com/swagger-api/swagger-ui/pull/2568. Since loopback-swagger uses model name and method name to create operation ids, it should be enough to enable this Swagger UI option.

Having said that, we may need to upgrade our Explorer to the latest Swagger UI version, see #209.

**Comment by webocs** [comment]
What's the status on this? I'd really love to use this feature..
