### ISSUE TITLE
curl expanding [] in examples provided by the API explorer

### ISSUE THREAD

**Issue by hardillb** [strongloop/loopback-component-explorer#138]
I'm playing with the API explorer and I'm having real trouble getting filters to work at all, so I've been trying to use the curl examples and adding things a bit at a time.

Because filters use square brackets to wrap operators like where, or, inq you need to tell curl not to try and expand the content of these.

The curl command line argument --globoff will prevent the expansion. Please add it to example when filters are specified

**Comment by 0candy** [comment]
@crandmck ^

**Comment by crandmck** [comment]
Hi @hardillb Thanks....Please note that you have to use "stringified JSON" for filters in API Explorer - see https://docs.strongloop.com/display/LB/Querying+data#Queryingdata-api-exp.  Since you brought this to my attention, I'll add this notice in a few other places, too.

I also added a note about using -g in a couple places:
- https://docs.strongloop.com/display/LB/LoopBack+FAQ#LoopBackFAQ-WhydocurlrequeststomyLoopBackappfail?
- https://docs.strongloop.com/display/LB/Querying+data

I added `-g` to a couple curl examples.  Please let me know if there are other curl examples that need it but I missed.  I'm going to close this, but I'll address any that you bring to my attention.
